spring:
  mail:
    to: vitekman@mail.ru
    host: smtp.yandex.ru
    port: 465
    username: tester-task08@yandex.ru
    password: yrnmimgtveowlubi
    protocol: smtps
    properties:
      smtp:
        auth: true
        ssl:
          enable: true
  application:
    name: taskmanagement
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks_data
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-main.yml
    default-schema: public
  kafka:
    bootstrap-servers: localhost:9092
    group-id: task-status-group
    topic:
     name: task-status-topic
    consumer:
      max-poll-records: 5
#logging:
#  level:
#    org.apache.kafka: INFO
#    root: INFO
#    com:
#      task.management.controllers.TaskController: DEBUG
#  pattern:
#    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /api/v1
  swagger-ui:
    path: /api/v1/doc
api:
  logging:
    enabled: true
    level: WARN